<a href="https://colab.research.google.com/github/brunaquignoli/InteligenciaArtificialUMC/blob/main/Exerc%C3%ADcios_DataScience_BrunaDias6BNoite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercícios de NumPy**

Professor, eu gostaria de iniciar pedindo perdão pelos comentários explicativos da atividade anterior, pois agora lendo o pdf que você mandou pra atividade atual, entendo o que quis dizer e que fiz de maneira completamente errada na atividade passada, então explicarei as resoluções de maneira correta agora!

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.


In [ ]:
import numpy as np
array = np.random.randint(10, 101, 50)
array.sort()
print(f"array de números aleatórios: {array}")

array de números aleatórios: [ 10  13  14  14  16  17  19  21  24  27  28  31  32  32  36  37  37  40
  40  43  45  46  47  51  52  52  53  56  56  63  65  66  66  67  68  69
  69  72  74  75  75  77  80  82  82  85  89  90 100 100]


Eu iniciei escolhendo np random radint pra gerar números entre 10, 101 e defini que deveriam ser 50 números, também arrumei os dados no array utilizando sort e exibi eles no final.

2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última
linha.

In [ ]:

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
ultima_linha = array[-1]
print(f"última linha da matriz: {ultima_linha}")

última linha da matriz: [13 14 15 16]


Utilizei o array pra criar um vetor 4x4 e utilizei [-1] pra pegar a última linha e depois exibi ela. (E não precisei importar o pandas de novo já que o primeiro serve para todos)

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
à 10ª posição por 1.

In [ ]:
array = np.zeros(15)
array[4:10] = 1
print(f"array com valores alterados: {array}")

array com valores alterados: [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Utilizei np.zeros (Que inclusive eu descobri que existe a partir da documentação) para gerar os 0, após isso fiz o fatiamento para inserir 1 aonde foi requisitado no enunciado.


4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e
a moda dos valores.


In [ ]:
import numpy as np

array = np.random.randint(1, 101, 100)
array.sort()
mediana = np.median(array)
moda = np.bincount(array).argmax()

print(array)
print(f"mediana: {mediana} | moda: {moda} ")


[ 2  4  6  9  9 11 11 12 12 13 14 14 15 16 18 18 18 21 23 24 24 24 25 26
 26 29 30 32 34 34 35 37 37 37 38 38 39 40 40 40 41 42 42 43 46 47 48 49
 50 50 50 51 52 52 54 56 59 62 63 64 64 66 67 70 71 72 72 72 73 73 74 74
 75 76 77 77 78 79 80 80 81 82 84 84 85 85 87 87 87 87 89 89 91 91 92 92
 94 97 97 98]
mediana: 50.0 | moda: 87 


Professor, aqui eu gerei o array a partir de uma definicao de que omaior numero seria 100, então arrumei os numeros para facilitar na visualização, calculei amodaemediana a partir de funcoes que encontrei logo na documentação do numpy.

5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por-3.


In [ ]:
array = np.random.randint(1, 101, 20)
print(f"array inicial: {array}")
array[array % 3 == 0] = -3
print(f"array final: {array}")


array inicial: [12 40 76 13 26 10  2 37 41  9 85 20 17 14 30 81 23 65 97 15]
array final: [-3 40 76 13 26 10  2 37 41 -3 85 20 17 14 -3 -3 23 65 97 -3]


Parofessor, aqui eu criei o array definindo que eram 20 numeros entre 1 e 100, mostrei o array inicial, mudei os multiplos de 3 para -3 a partir de uma modificacao de array e printei o resultado.

6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna.


In [ ]:
matriz = np.random.rand(5, 5)
print(matriz)
soma_colunas = np.sum(matriz, axis=0)
print(soma_colunas)

[[0.35676329 0.09897757 0.46848988 0.09378186 0.40149931]
 [0.18583515 0.38335022 0.47611421 0.03168459 0.64918664]
 [0.05719965 0.92015342 0.75167193 0.95396653 0.99830621]
 [0.83317916 0.99711056 0.84465981 0.46298079 0.3662464 ]
 [0.25071457 0.13304186 0.45536151 0.02412615 0.49442176]]
[1.68369183 2.53263363 2.99629735 1.56653992 2.90966031]


utilizei random.rand ao invés de randint para pegar números não inteiros aleatórios, o np.sum faz a soma das colunas a partir do array matriz passado lá dentro, e o axis 0, que é  a dimensão da soma.

7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.


In [ ]:
import numpy as np
array = np.random.randint(1, 101, 20)
array2 = np.random.randint(1, 101, 20)

print(array)
print(array2)
resultado = np.corrcoef(array, array2)
print(resultado)

[52 34 73 78 12 47 47 66 51  8  6 95 88 97 13 17 24 21 92  5]
[33 95 98 38  7 67 18 66 76 18 50  9 10 28 50 40 17 68 96 50]
[[1.         0.06869303]
 [0.06869303 1.        ]]


np.corrcoef retorna a correlação entre dois arrays passados, então nesse exercício eu resolvi criar os dos arraus aleatórios e passá-los na função.

8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.


In [ ]:
matriz = np.random.randint(1, 11, 9)
matriz = matriz.reshape(3, 3)
print(matriz)
matriz = np.square(matriz)
print(matriz)

[[8 6 3]
 [9 2 4]
 [2 1 2]]
[[64 36  9]
 [81  4 16]
 [ 4  1  4]]


utilizei random.randint para criar o array e reshape paraarrumar em matriz 3x3, depois o np.square faz o quadrado para poder exibir

9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.


In [ ]:
array = np.random.rand(10)
print(array)
array = (array - np.min(array)) / (np.max(array) - np.min(array))
print(array)

[0.05129531 0.41110037 0.09590035 0.46266448 0.22027149 0.90828146
 0.35059857 0.68878118 0.71243097 0.49257595]
[0.         0.41984933 0.05204872 0.48001846 0.19717493 1.
 0.34925099 0.74386951 0.77146598 0.51492155]


utilizei random.rand ao invés de randint para pegar números não inteiros aleatórios novamente, e fiz uma normalização, onde fiz array - o valor mínimo, dividido pelo máximo do array - o mínimo.

10. Crie umamatriz identidade 6x6 e substitua a diagonal principal por valores
crescentes de 1 a 6.


11. Gere um array de 100 números inteiros e encontre o valor que mais se
repete no array.


In [ ]:
array = np.random.randint(0, 100, 100)
valores, contagens = np.unique(array, return_counts=True)
frequente = valores[np.max(contagens)]

print(f"o valor mais frequente é {frequente}")


o valor mais frequente é 4


12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.


In [ ]:
matriz = np.random.randint(0, 101, 16).reshape(4,4)
np.fill_diagonal(matriz, 7)
print(matriz)

[[  7   3  55  22]
 [ 45   7   0   7]
 [100  91   7 100]
 [ 20  66   9   7]]


13. Crie um array contendo os 10 primeiros números pares e calcule sua soma
cumulativa.


In [ ]:
array = np.arange(0, 21, 2)
soma = np.sum(array)

print(f"A soma é {soma}")
print(f"E o array é: {array}")

A soma é 110
E o array é: [ 0  2  4  6  8 10 12 14 16 18 20]


14. Calcule a diferença entre dois arrays de números aleatórios de mesmo
comprimento e encontre a média das diferenças.


In [ ]:
array1 = np.random.randint(0, 101 , 5)
array2 = np.random.randint(0, 101 , 5)

dif = array1 - array2
media = np.median(dif)
print(media)

11.0


fiz random.randint para pegar 5 números inteiros aleatórios entre 0 e 100, fiz uma subtração entre eles e utilizei np.median da subtração, printando esse resultado ao final.

15. Gere um array contendo 20 números e substitua todos os valores maiores
que 50 por 50.


In [ ]:
array = np.random.randint(0, 101, 20)
array[array > 50] = 50
print(array)

[29 50 50  2 49 50 39 50 50 12 50 50 21 50 45  3 50  6 50 41]


utilizei random.randint para pegar 20 números aleatórios entre 0 e 100, então fiz uma modificação direta no array onde os maiores de 50 seriam substituídos por 50, então printando o array.

16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.


In [ ]:
array = np.random.randint(0, 101, 12)
array = array.reshape(3, 4)
print(array)

[[18 89 66 27]
 [43 54 42  3]
 [91 66 15 74]]


Utilizei random.randint para pegar 12 números inteiros aleatórios entre 0 e 100 e utilizei reshape para reorganizar, passando 3 e 4 para definir o tamanho da matriz, então apresentando esses dados.

17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada
valor por sua posição na matriz.

In [ ]:
matriz = np.random.randint(0, 101, 16).reshape(4,4)
indices = np.arange(1, 17).reshape(4, 4)
resultado = matriz * indices
print(resultado)

[[  21   14  297   44]
 [ 440  558  189  464]
 [ 351  650  297 1188]
 [ 702  588  915 1552]]


utilizei random.randint para pegar 16 números entre 0 e 100, e já utilizei reshape para arrumar os números em uma matriz 4x4
depois utilizei o mesmo método para pegar números entre 1 e 16 (que seriam os indexes) e multipliquei as duas matrizes, exibindo o resultado.

18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 5 por 0.


In [ ]:
array = np.random.randint(0, 101, 10)
array[array % 5 == 0 ] = 0
print(array)

[ 0 37 19 16 73 56 27 49  0 21]


utilizei random.randint pra gerar números 10 inteiros aleatórios entre 1 e 100, então fiz uma alteração direta no array para substituir por 0 os divisíveis por 5, então exibi o array.

19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o
ângulo entre eles (produto escalar normalizado).


In [ ]:
array1 = np.random.randint(0, 101, 10)
array2 = np.random.randint(0, 101, 10)
angle = np.dot(array2, array1)
print(angle)

28456


 peguei dois arrays aleatórios e utilizei np.dot pra calcular o angulo, usando os dois arrays como parâmetro, então exibi o resultado.

20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada
linha

In [ ]:
matriz = np.random.randint(0, 101, 16).reshape(4,4)
print(matriz)
minimo = np.min(matriz, axis=1)
print(minimo)

[[70 19 80 86]
 [ 7 84  3 83]
 [15 23 29 48]
 [71 26 31 23]]
[19  3 15 23]


Aqui fiz um random.randint pra pegar os valores aleatórios e descobri que dá pra direto deixar eles como matriz usando reshape na mesma linha, depois utilizei np.min e axis 1 e printei