<a href="https://colab.research.google.com/github/brunaquignoli/InteligenciaArtificialUMC/blob/main/Exerc%C3%ADcios_DataScience_BrunaDias6BNoite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercícios de NumPy**

Professor, eu gostaria de iniciar pedindo perdão pelos comentários explicativos da atividade anterior, pois agora lendo o pdf que você mandou pra atividade atual, entendo o que quis dizer e que fiz de maneira completamente errada na atividade passada, então explicarei as resoluções de maneira correta agora!

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.


In [ ]:
import numpy as np
array = np.random.randint(10, 101, 50)
array.sort()
print(f"array de números aleatórios: {array}")

array de números aleatórios: [ 10  13  14  14  16  17  19  21  24  27  28  31  32  32  36  37  37  40
  40  43  45  46  47  51  52  52  53  56  56  63  65  66  66  67  68  69
  69  72  74  75  75  77  80  82  82  85  89  90 100 100]


Eu iniciei escolhendo np random radint pra gerar números entre 10, 101 e defini que deveriam ser 50 números, também arrumei os dados no array utilizando sort e exibi eles no final.

2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última
linha.

In [ ]:

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
ultima_linha = array[-1]
print(f"última linha da matriz: {ultima_linha}")

última linha da matriz: [13 14 15 16]


Utilizei o array pra criar um vetor 4x4 e utilizei [-1] pra pegar a última linha e depois exibi ela. (E não precisei importar o pandas de novo já que o primeiro serve para todos)

3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
à 10ª posição por 1.

In [ ]:
array = np.zeros(15)
array[4:10] = 1
print(f"array com valores alterados: {array}")

array com valores alterados: [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


Utilizei np.zeros (Que inclusive eu descobri que existe a partir da documentação) para gerar os 0, após isso fiz o fatiamento para inserir 1 aonde foi requisitado no enunciado.


4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e
a moda dos valores.


In [15]:
import numpy as np

array = np.random.randint(1, 101, 100)
array.sort()
mediana = np.median(array)
moda = np.bincount(array).argmax()

print(array)
print(f"mediana: {mediana} | moda: {moda} ")


[ 2  4  6  9  9 11 11 12 12 13 14 14 15 16 18 18 18 21 23 24 24 24 25 26
 26 29 30 32 34 34 35 37 37 37 38 38 39 40 40 40 41 42 42 43 46 47 48 49
 50 50 50 51 52 52 54 56 59 62 63 64 64 66 67 70 71 72 72 72 73 73 74 74
 75 76 77 77 78 79 80 80 81 82 84 84 85 85 87 87 87 87 89 89 91 91 92 92
 94 97 97 98]
mediana: 50.0 | moda: 87 


Professor, aqui eu gerei o array a partir de uma definicao de que omaior numero seria 100, então arrumei os numeros para facilitar na visualização, calculei amodaemediana a partir de funcoes que encontrei logo na documentação do numpy.

5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por-3.


In [14]:
array = np.random.randint(1, 101, 20)
print(f"array inicial: {array}")
array[array % 3 == 0] = -3
print(f"array final: {array}")


array inicial: [12 40 76 13 26 10  2 37 41  9 85 20 17 14 30 81 23 65 97 15]
array final: [-3 40 76 13 26 10  2 37 41 -3 85 20 17 14 -3 -3 23 65 97 -3]


Parofessor, aqui eu criei o array definindo que eram 20 numeros entre 1 e 100, mostrei o array inicial, mudei os multiplos de 3 para -3 a partir de uma modificacao de array e printei o resultado.

6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna.


In [23]:
array = np.arange(25)
matriz = array.reshape(5, 5)

print(matriz)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.


8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.


9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.


10. Crie umamatriz identidade 6x6 e substitua a diagonal principal por valores
crescentes de 1 a 6.


11. Gere um array de 100 números inteiros e encontre o valor que mais se
repete no array.


12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.


13. Crie um array contendo os 10 primeiros números pares e calcule sua soma
cumulativa.


14. Calcule a diferença entre dois arrays de números aleatórios de mesmo
comprimento e encontre a média das diferenças.


15. Gere um array contendo 20 números e substitua todos os valores maiores
que 50 por 50.


16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.


17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada
valor por sua posição na matriz.

18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 5 por 0.


19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o
ângulo entre eles (produto escalar normalizado).


20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada
linha